version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/django
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    
    image: application:django
    container_name: django_app
    command: gunicorn django_curd.wsgi:application --bind 0.0.0.0:8000
    # depends_on:
    #   - db

  # db:
  #   image: postgres:14
  #   environment:
  #     POSTGRES_USER: django
  #     POSTGRES_PASSWORD: django
  #     POSTGRES_DB: mydatabase
  #   ports:
  #     - "5432:5432"
