services:
  web:
    build: .
    volumes:
      - .:/django
      - ./media:/django/media
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"  # Use string values for boolean environment variables
    image: application:django
    container_name: django_app
    # command: gunicorn django_curd.wsgi:application --bind 0.0.0.0:8000
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    # depends_on:
    #   - db

#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: curd_app
#       MYSQL_USER: root
#       MYSQL_PASSWORD: root
#     volumes:
#       - mysql_data:/var/lib/mysql
#     ports:
#       - "3307:3306"  # Expose MySQL port for local connections
#     restart: always  # Ensure the DB container restarts automatically if it fails

# volumes:
#   mysql_data:  # Volume definition for persistent MySQL storage
