services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEBUG=False  # Ensure DEBUG is False for production
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py collectstatic --noinput &&
             gunicorn django_curd.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: django_curd.settings.production
    volumes:
      - ./django:/django
      - ./media:/django/media
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    depends_on:
      - db

  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: curd_app
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./django:/django
      - ./media:/django/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

# volumes:
#   mysql_data:
