name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Run commands on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-54-175-193-166.compute-1.amazonaws.com << 'EOF'
          cd django_curd
          git pull origin master
          docker compose -f prod.yml restart web
        EOF
